### ISSUE TITLE
Cannot install with td-agent-gem 

### ISSUE THREAD

**Issue by bstabens** [moccos/fluent-plugin-websocket#12]
When trying to install with
 td-agent-gem install fluent-plugin-websocket
it fails with
```
Fetching eventmachine-1.2.7.gem
Fetching fluent-plugin-websocket-0.1.8.gem
Fetching em-websocket-0.5.2.gem
Building native extensions. This could take a while...
ERROR:  Error installing fluent-plugin-websocket:
        ERROR: Failed to build gem native extension.

    current directory: /opt/td-agent/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/ext
/opt/td-agent/bin/ruby -I /opt/td-agent/lib/ruby/2.7.0 -r ./siteconf20210210-47441-wm4dlm.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/td-agent/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-crypto-dir
        --without-crypto-dir
        --with-crypto-include
        --without-crypto-include=${crypto-dir}/include
        --with-crypto-lib
        --without-crypto-lib=${crypto-dir}/lib
        --with-cryptolib
        --without-cryptolib
/opt/td-agent/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:801:in `try_func'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:1029:in `block in have_library'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:331:in `open'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:331:in `open'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
        from /opt/td-agent/lib/ruby/2.7.0/mkmf.rb:1024:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/td-agent/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/td-agent/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7 for inspection.
Results logged to /opt/td-agent/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/gem_make.out
```
Logged results here:
```
 "gcc -o conftest -I/opt/td-agent/include/ruby-2.7.0/x86_64-linux -I/opt/td-agent/include/ruby-2.7.0/ruby/backward -I/opt/td-agent/include/ruby-2.7.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fdebug-prefix-map=/build/td-agent-4.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/opt/td-agent/lib -Wl,-rpath,/opt/td-agent/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/opt/td-agent/lib -L/opt/td-agent/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

package configuration for openssl is not found
```

I am clueless as to what to do next.

**Comment by bstabens** [comment]
Issue fixed after 
apt install build-essential libdev-ssl
