### ISSUE TITLE
Error on fluentd:v1.10-1

### ISSUE THREAD

**Issue by gimmi** [moccos/fluent-plugin-websocket#8]
I am triying to run the plugin into the doker image:

```
fluent/fluentd:v1.10-1
```

But I get this error:

```
2020-04-29 08:15:16 +0000 [debug]: adding store type="websocket"
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        36: from /usr/bin/fluentd:23:in `<main>'
        35: from /usr/bin/fluentd:23:in `load'
        34: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'
        33: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        32: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        31: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
        30: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:551:in `run_supervisor'
        29: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/engine.rb:80:in `run_configure'
        28: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/engine.rb:105:in `configure'
        27: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/root_agent.rb:146:in `configure'
        26: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `configure'
        25: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `each'
        24: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:74:in `block in configure'
        23: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:132:in `add_match'
        22: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/plugin.rb:173:in `configure'
        21: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/plugin/out_copy.rb:38:in `configure'
        20: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/plugin/multi_output.rb:63:in `configure'
        19: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/plugin/multi_output.rb:63:in `each'
        18: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/plugin/multi_output.rb:72:in `block in configure'
        17: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/plugin.rb:109:in `new_output'
        16: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/plugin.rb:155:in `new_impl'
        15: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:44:in `lookup'
        14: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:99:in `search'
        13: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:99:in `each'
        12: from /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:102:in `block in search'
        11: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-websocket-0.1.8/lib/fluent/plugin/out_websocket.rb:15:in `<top (required)>'
         8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
         6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
         5: from /usr/lib/ruby/gems/2.5.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `<top (required)>'
         4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         2: from /usr/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so) - /usr/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so (LoadError)
```

The installation of the plugin via the `Dockerfile` seems ok:

```
Building native extensions. This could take a while...
Successfully installed eventmachine-1.2.7
Successfully installed em-websocket-0.5.1
Successfully installed fluent-plugin-websocket-0.1.8
3 gems installed
```

**Comment by gimmi** [comment]
I fixed the error by adding the following to the `Dockerfile`:

```
RUN apk add --no-cache libstdc++
```
